development:
  secret_key_base: d21c22818be94101b341d934ba633b9b3a81c309ea8c5897e048832ee6fffd822bbceb147c80002e4009513ac737672d6db641fc3a8a512a9b527718e523f011
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
test:
  secret_key_base: d21c22818be94101b341d934ba633b9b3a81c309ea8c5897e048832ee6fffd822bbceb147c80002e4009513ac737672d6db641fc3a8a512a9b527718e523f011
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>